spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand?userUnicode=true&characterEncodeing=utf-8&useSSL=true&useAffectedRows=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化大小
      initial-size: 5
      max-active: 100
      min-idle: 5
      #获得连接等待时间
      max-wait: 600000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时检测连接是否有效
      test-on-borrow: false
      # 归还连接时检测连接是否有效
      test-on-return: false
      # 打开PSCache,并且指定每个连接上的PSCache大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        # allow: 127.0.0.1
        # druid访问地址:http://localhost:port/context-path/druid/login.html 账号&密码
        login-username: admin
        login-password: 123456